version: "3"

services:
  teapot:
    image: application:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql/teapot?user=teapot&password=teapot
    ports:
      - ${EXPOSED_TEAPOT_PORT:-8080}:8080

  postgresql:
    image: postgres:13.1-alpine
    ports:
      - ${EXPOSED_POSTGRESQL_PORT:-5432}:5432
    environment:
      POSTGRES_DB: teapot
      POSTGRES_USER: teapot
      POSTGRES_PASSWORD: teapot

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - ${EXPOSED_PROMETHEUS_PORT:-9090}:9090

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/conf/custom.ini:/usr/share/grafana/conf/custom.ini:ro
    ports:
      - ${EXPOSED_GRAFANA_PORT:-3000}:3000
