logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-enabling-endpoints
management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: 'health,prometheus'

server:
  tomcat:
    connection-timeout: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost/teapot?user=teapot&password=teapot
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: teapot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        use_sql_comments: true
    open-in-view: false

springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    enabled: true
