global:
  scrape_interval: 15s

scrape_configs:
  - job_name: teapot
    metrics_path: /actuator/prometheus
    static_configs:
      - labels:
          app: teapot
      - targets:
          - teapot:8080
  - job_name: prometheus
    static_configs:
      - labels:
          app: prometheus
      - targets:
          - prometheus:9090
  - job_name: grafana
    static_configs:
      - labels:
          app: grafana
      - targets:
          - grafana:3000
