apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: 53d0e212-a596-49e6-968e-038888cd1376
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
